### ISSUE TITLE
can not build vrp on 64 bit machine

### ISSUE THREAD

**Issue by svigerske** [coin-or/SYMPHONY#104]
Issue created by migration from Trac.

Original creator: @ashutoshmahajan

Original creation time: 2009-10-28 23:19:25

Assignee: @tkralphs

Version: 

The vrp application does not compile with g++ 4.3.2 and  g++ 4.2.4. It throws following error messages. Changing int to long int in the code seems to fix the problem.
```
/home/mahajan/src/sym-trunk/SYMPHONY/src/../Applications/VRP/src/Master/vrp_master_functions.c:73: error: cast from ‘edge_data*’ to ‘int’ loses precision
/home/mahajan/src/sym-trunk/SYMPHONY/src/../Applications/VRP/src/Master/vrp_master_functions.c:73: error: cast from ‘edge_data*’ to ‘int’ loses precision
/home/mahajan/src/sym-trunk/SYMPHONY/src/../Applications/VRP/src/Master/vrp_master_functions.c:73: warning: conversion to ‘int’ from ‘long unsigned int’ may alter its value
make: *** [src/vrp_master_functions.o] Error 1
```
