### ISSUE TITLE
SYMPHONY-5.6.14 fails to compile with clang-8.0.0

### ISSUE THREAD

**Issue by ycollet** [coin-or/SYMPHONY#167]
I compile SYMPHONY-5.6.14 under Fedora 30 with clang 8.0.0.

An error shows up during compilation:
```
SYMPHONY-5.6.14/src/EP_SYMPHONY/SYMPHONY/src/LP/lp_genfunc.c:2427:28: error: ordered comparison between pointer and zero ('int *' and 'int')
      if(i < 0 && num_cuts > 0) should_stop = TRUE;
                  ~~~~~~~~ ^ ~
```

**Comment by tkralphs** [comment]
Yes, thanks! This has been fixed in the latest release (5.6.17).
